### ISSUE TITLE
Perform test and optimization of stream data

### ISSUE THREAD

**Issue by gsi-dayanacaridad** [generalsoftwareinc/DeribitServiceClient#14]
- [x]   (@gsi-yoancme ) Refactor to optimize message reading on WebSocket.
- [x]    (@gsi-robertogarcia )  Refactor to optimize to reduce the trigger of garbage collection 
- [x]   (@gsi-juandavid) Refactor to remove the hardcoded value, add static const value with all methods used in the Deribit socket client
- [x]  (@gsi-yoancme) Refactor to improve the readability of base code
- [x]   (@gsi-yoancme) Refactor to improve the option validations and dependency injection

**Comment by gsi-robertogarcia** [comment]
Looks good to me
