### ISSUE TITLE
Create a pre-commit hook to format the code, following the style guide suggested for .Net 7

### ISSUE THREAD

**Issue by gsi-dayanacaridad** [generalsoftwareinc/DeribitServiceClient#24]

**Comment by gsi-pujol** [comment]
To use this pre-commit hook, save the code as .git/hooks/pre-commit.cmd in your repository, and make sure it is executable (e.g. by running attrib +x .git/hooks/pre-commit.cmd in a Command Prompt).

[pre-commit.cmd.txt](https://github.com/generalsoftwareinc/DeribitServiceClient/files/10709913/pre-commit.cmd.txt)

**Comment by gsi-yoancme** [comment]
LGTM!
